In [3]:
print("hello world")

hello world


In [4]:
print(4+2)

6


In [5]:
print("4+2")

4+2


In [9]:
print("godfrey nazuan")

godfrey nazuan


### comments

In [10]:
# printing a text ai is the future
print("AI IS THE FUTURE")

AI IS THE FUTURE


### comments

In [11]:
# Addition Example
print(5+6)

11


### Variables

In [12]:
x=12

In [13]:
x

12

In [15]:
print(x)

12


In [16]:
x+2

14

In [17]:
y=5

In [19]:
# 12 + 5
x+y

17

In [20]:
firstname = "Ayomide"

In [21]:
firstname

'Ayomide'

In [22]:
# Create a variable called lastname, assign a valu/text and print it out

In [23]:
Lastname = "Godfrey"

In [27]:
print(Lastname)

Godfrey


In [28]:
3

3

In [29]:
print(3)
5

3


5

In [30]:
print(3)
print(5)

3
5


In [31]:
firstname

'Ayomide'

In [32]:
Lastname

'Godfrey'

In [33]:
2star=4

SyntaxError: invalid decimal literal (2120998569.py, line 1)

In [34]:
star2=4

In [37]:
my_var= 6

In [36]:
my-var=6

SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (2273541058.py, line 1)

### DATA TYPES

In [38]:
x=5

In [40]:
type(x)

int

In [41]:
y=10

In [42]:
type(y)

int

In [43]:
q=4.5

In [44]:
type(q)

float

In [45]:
w=45.4232

In [46]:
type(w)

float

In [49]:
# String
Firtname = "ayomide"
type(Firtname)

str

In [50]:
type("this is a string")

str

In [53]:
c= "10"

In [55]:
type(c)

str

In [ ]:
# list

In [56]:
mylist = ["bmw", "benz", "mazda", "rolls royce", "Chevrolet"]

In [57]:
type(mylist)

list

In [58]:
mylist

['bmw', 'benz', 'mazda', 'rolls royce', 'Chevrolet']

In [59]:
c

'10'

In [60]:
x

5

In [61]:
w

45.4232

In [62]:
# TUPLE - IMMUTABLE
a = (2, 4, 5, "String")

In [63]:
a

(2, 4, 5, 'String')

In [64]:
type(a)

tuple

In [107]:
# Dictionary
users = {"name": "Ayomide", "state": "lagos", "age": 30}

In [68]:
type(users)

dict

In [74]:
login= {"email": "abc@d.com", "password": 1234445}
login

{'email': 'abc@d.com', 'password': 1234445}

In [76]:
type(login)

dict

In [77]:
#BOOL

In [78]:
3 < 5

True

In [79]:
type(3 < 5)

bool

### Casting
is the act of converting one data type to another data type. e.g string to intger, intger to float

In [80]:
a=10

In [82]:
# Converting intger to String
c= str(a)

In [83]:
c

'10'

In [84]:
b = 10.5

In [86]:
d=int(b)

In [87]:
b

10.5

In [88]:
10

10

In [89]:
float(10)

10.0

In [90]:
f=4

In [91]:
float(f)

4.0

### Arithemetic Operators
* Addition
* Subtraction
* Multiplication
* Division
* Exponentiation
* Modulus

### Addition

In [94]:
a=5
b=10

In [95]:
c= a+b

In [96]:
c

15

### Subtraction

In [97]:
x=4
y=9

In [98]:
print(y-x)

5


### Multiplication

In [99]:
a=10
b=3

In [100]:
a*b

30

### Division

In [101]:
c=90
b=3
d=c/b
d

30.0

### Exponenitation

In [103]:
a = 2

In [104]:
a**2

4

### Modulus (reminder)

In [105]:
c=10
b=3

In [106]:
c%b

1

In [116]:
users= {"name": "ayomide", "state": "bayelsa","age": 30, "nationality": ["english", "nigeria"]}

In [118]:
type(users)

dict

### Logical Operators
AND,OR, NOT

In [121]:
a=10
b=6
c=12

In [120]:
a<b

False

In [122]:
#OR
a<b or a>c

False

In [127]:
c > b | b > a | a > c

False

# AND

In [128]:
a < c and b > a

False

In [129]:
 c < b and a < b

False

In [130]:
# NOT
not(a < b)

True

In [131]:
not(c > a)

False

### LIST
is a data type that start with square bracket[]

In [133]:
mylist = [2,4,3, "orange", "apple"]

In [134]:
mylist

[2, 4, 3, 'orange', 'apple']

In [135]:
# List Indexing trying to fetch something out of the list
mylist[3]


'orange'

In [138]:
mylist[1]

4

In [139]:
print(mylist[4])
print(mylist[-1])

apple
apple


In [140]:
# fetech orange and apple
mylist[3:5]
whenever you are dealing with range always add one

['orange', 'apple']

In [141]:
mylist[1:4]

[4, 3, 'orange']

In [268]:
thislist = ["apple", "banana", "cherry", "apple", "pineapple", "kiwi", "orange"]
print(thislist)

['apple', 'banana', 'cherry', 'apple', 'pineapple', 'kiwi', 'orange']


In [269]:
print(thislist[0:4])
print(thislist[:4])

['apple', 'banana', 'cherry', 'apple']
['apple', 'banana', 'cherry', 'apple']


In [160]:
print(thislist[3:7])
print(thislist[3:])

['apple', 'pineapple', 'kiwi', 'orange']
['apple', 'pineapple', 'kiwi', 'orange']


In [161]:
Carlist = ["Benz", "Bmw", "lexus", "corola", "Land Rover", "range rover", "peguot"]

In [271]:
Carlist[4:7]

['Land Rover', 'range rover', 'peguot']

In [272]:
print(Carlist[4:7])

['Land Rover', 'range rover', 'peguot']


In [273]:
thislist.append("mango")

In [274]:
thislist = ["apple", "banana", "cherry", "melon", "pineapple", "kiwi", "orange"]


In [275]:
thislist.remove("orange")

In [276]:
thislist

['apple', 'banana', 'cherry', 'melon', 'pineapple', 'kiwi']

In [277]:
thislist.append("sugarcane")

In [170]:
thislist

['apple', 'banana', 'cherry', 'melon', 'pineapple', 'kiwi', 'sugarcane']

In [172]:
#Clear all items from the list
thislist.clear()

In [173]:
thislist

[]

### IF ELSE

In [174]:
a=20

In [175]:
if a < 15:
    print("a is less than fifteen")
else:
    print("a is not less than fifteen")

a is not less than fifteen


In [176]:
age = 12

In [179]:
if age < 18:
    print ("you're not allowed to enter")
else:
    print("Acesss granted")

you're not allowed to enter


In [183]:
password = 1234
if password == 1234:
    print("invalid Login")
else:
    print("login Sucessful")


invalid Login


In [641]:
# Simulating a website login using if else
username = "moore"
password = 12345
email = "moore@gmail.com"

In [195]:
if username == "moore" and password == 1234:
    print("Login Sucessfull")
else:
    print("invalid Login details")

invalid Login details


In [638]:
if (username == "moore" or email == "moore@gmail.com") and password == 1234555:
    print("login sucessful")
else:
    print("invalid login details")

invalid login details


In [200]:
age = 35

In [201]:
if age < 18:
    print("minor")
elif age < 51:
    print("adult")
else:
    print("old")


adult


### BMI Calculator


* Classification	BMI range - kg/m2
* Severe Thinness	< 16
* Moderate Thinness	16 - 17
* Mild Thinness	17 - 18.5
* Normal	18.5 - 25
* Overweight	25 - 30
* Obese Class I	30 - 35
* Obese Class II	35 - 40
* Obese Class III	> 40


In [213]:
BMI = 10

In [214]:
if BMI < 16:
    print("severe Thinness")
elif BMI <= 17:
    print("moderate Thiness")
elif BMI <=18.5:
    print("Mild Thiness")
elif BMI <=25:
    print("Normal")
elif BMI <=30:
    print("Overweight")
elif BMI <=35:
    print("Obese Class I")
elif BMI <=40:
    print("Obese Class II")
else: 
    print:("Obese Class III")

severe Thinness


### Dictionary

In [215]:
users = {"username": "techpriest", "password": 12345}

In [216]:
users

{'username': 'techpriest', 'password': 12345}

In [217]:
users.values()

dict_values(['techpriest', 12345])

In [218]:
users.keys()

dict_keys(['username', 'password'])

In [241]:
Products = {"product name": "nivea", "Describtion": "This is a nivea body cream", "Tags": ["lotion","dark","cream", "beauty"]}

In [242]:
Products.values()

dict_values(['nivea', 'This is a nivea body cream', ['lotion', 'dark', 'cream', 'beauty']])

In [243]:
Products.keys()

dict_keys(['product name', 'Describtion', 'Tags'])

In [244]:
Products["Describtion"]

'This is a nivea body cream'

In [245]:
Products["product name"]

'nivea'

In [246]:
Products

{'product name': 'nivea',
 'Describtion': 'This is a nivea body cream',
 'Tags': ['lotion', 'dark', 'cream', 'beauty']}

In [250]:
Products["product name"] = "okain"

In [251]:
Products

{'product name': 'okain',
 'Describtion': 'This is a nivea body cream',
 'Tags': ['lotion', 'dark', 'cream', 'beauty'],
 'Product name': 'okain'}

In [254]:
Products["Describtion"] = "this is a body soap"

In [255]:
Products

{'product name': 'okain',
 'Describtion': 'this is a body soap',
 'Tags': ['lotion', 'dark', 'cream', 'beauty'],
 'Product name': 'okain',
 'describtion': 'this is a body soap'}

In [256]:
Products["price"] = 5000

In [257]:
Products

{'product name': 'okain',
 'Describtion': 'this is a body soap',
 'Tags': ['lotion', 'dark', 'cream', 'beauty'],
 'Product name': 'okain',
 'describtion': 'this is a body soap',
 'price': 5000}

In [258]:
Products["Tags"] = ["soap", "dark", "cream", "beauty"]

In [260]:
Products

{'product name': 'okain',
 'Describtion': 'this is a body soap',
 'Tags': ['soap', 'dark', 'cream', 'beauty'],
 'Product name': 'okain',
 'describtion': 'this is a body soap',
 'price': 5000}

In [261]:
Products

{'product name': 'okain',
 'Describtion': 'this is a body soap',
 'Tags': ['soap', 'dark', 'cream', 'beauty'],
 'Product name': 'okain',
 'describtion': 'this is a body soap',
 'price': 5000}

In [264]:
Products.pop("price", 'Tags')

'Tags'

In [265]:
Products

{'product name': 'okain',
 'Describtion': 'this is a body soap',
 'Tags': ['soap', 'dark', 'cream', 'beauty'],
 'Product name': 'okain',
 'describtion': 'this is a body soap'}

In [266]:
Products.clear()

In [267]:
Products

{}

### GRADING SYSTEM

* F < 45
* d 45-50
* c 50-59
* b 60-69
* a> 69

In [311]:
Grade = 65

In [312]:
if Grade < 45:
    print ("F")
elif Grade <= 50:
    print ("D")
elif Grade <=59:
    print ("c")
elif Grade <=69:
    print ("b")
else:
    print ("a")

b


### Assignment Operators

In [313]:
x =5

In [314]:
x + 2

7

In [315]:
x= x + 6

In [316]:
x

11

In [317]:
# x = x + 6
x += 6
x

17

In [318]:
a = 10
a -= 3
a

7

### While Loop

In [319]:
x = 2

In [320]:
while x < 10:
    print(x)
    x += 1

2
3
4
5
6
7
8
9


In [321]:
x=2

In [322]:
while x <=20:
    print (x)
    x+=2

2
4
6
8
10
12
14
16
18
20


### Odd Numbers

In [323]:
x=1

In [324]:
while x <= 19:
    print (x)
    x+=2

1
3
5
7
9
11
13
15
17
19


### For Loop

In [325]:
fruits = ["apple", "pineapple", "cherry"]
fruits

['apple', 'pineapple', 'cherry']

In [326]:
for i in fruits:
    print (i)

apple
pineapple
cherry


In [327]:
range (6)

range(0, 6)

In [328]:
for x in range (6):
    print (x)

0
1
2
3
4
5


In [329]:
range (10)

range(0, 10)

In [330]:
for e in range (10):
    print (e)

0
1
2
3
4
5
6
7
8
9


In [331]:
# Start at 2
range (2, 10)

range(2, 10)

In [332]:
for c in range (2, 10):
    print (c)

2
3
4
5
6
7
8
9


In [333]:
colors = ["red", "blue", "green"]

In [335]:
for i in fruits:
    for y in colors:
        print(i, y)

apple red
apple blue
apple green
pineapple red
pineapple blue
pineapple green
cherry red
cherry blue
cherry green


In [338]:
## Dictionary has key value pairs


In [339]:
users = {"name": "ayomide", "age": 19}
users

{'name': 'ayomide', 'age': 19}

In [340]:
users.keys()

dict_keys(['name', 'age'])

In [341]:
users.values()

dict_values(['ayomide', 19])

In [342]:
for x in users.values():
    print(x)

ayomide
19


### FUNCTIONS

a function is a block of code which only runs when it is called. you can pass datas known as patameters into functions. 
A function can return datas as result


In [344]:
def myfunction():
    print("hello from the fuction world")

In [345]:
myfunction()

hello from the fuction world


In [346]:
# a function that takes in two numbers and adds it together 
def addition(x,y):
    c = x + y
    print(c)
    

In [347]:
addition(3,7)

10


In [348]:
addition(7,10)

17


In [350]:
def substraction (r,w):
    b = r - w
    print(b)

In [352]:
substraction(10,5)

5


In [353]:
## passing aguments by default
def defaultparams(country= "UK"):
    print(country)

In [356]:
defaultparams()

UK


In [358]:
defaultparams("Nigeria")

Nigeria


In [359]:
defaultparams()

UK


In [367]:
def subtraction(a = 7, b = 2):
    c= b-a
    print(c)

In [368]:
subtraction()

-5


In [369]:
subtraction(10, 20)

10


In [380]:
def product(Name, brand, price = 10000):
    print (Name)
    print (brand)
    print (price)

In [381]:
product( "Godfrey", "Lexus", "2000000")

Godfrey
Lexus
2000000


In [390]:
def circle(pi = 3.14, r):
    A= 3.14 * r**2
    print(A)

SyntaxError: parameter without a default follows parameter with a default (467149882.py, line 1)

In [397]:
# Correction

def circle(r, pi = 3.14):
    area = pi * (r ** 2)
    print(area)

In [398]:
circle(r=7)

153.86


In [401]:
def triangle(b, h):
    A= 0.5 * b * h
    print (A)

In [408]:
triangle(5,9)

22.5


In [444]:
def trapizum(a, b, h):
    c= a + b
    A= 0.5 * c * h
    print (A)

In [420]:
trapizum(1,2,3)

4.5


In [421]:
0.5 * 9

4.5

In [422]:
email = "moore@gmail.com"
password = 12345

In [423]:
if email == "moore@gmail.com" and password == 12345:
    print("login Sucessful")
else:
    print("invalid login details")

login Sucessful


In [424]:
def login(email, password):
    if email == "moore@gmail.com" and password == 12345:
        print("login Succesful")
    else:
        print("invalid login details")

In [425]:
login("hgdjhfvhcgdgbd@gmail.com", 12345)

invalid login details


In [427]:
login("moore@gmail.com", 12345)

login Succesful


In [489]:
## Assignment.. True for Even, false for Odd numbers.

def is_even (num):
    if num % 2 == 0:
        print ("true")
    else:
        print ("false")

In [477]:
is_even(6)

true


In [478]:
x=6

In [479]:
while x < 10:
    print(x)
    x += 1

6
7
8
9


In [490]:
### True for odd, False for Even, != another way or writing not even!

def is_even(x):
    if x% 2 != 0:
        print(True)
    else:
        print(False)
    

In [484]:
is_even(9)

True


In [485]:
is_even(12)

False


In [486]:
def is_even(x):
    if x% 2 == 1:
        print(True)
    else:
        print(False)
    

In [487]:
is_even(9)

True


In [488]:
is_even(6)

False


### Strings

In [491]:
d= "this is a string"

In [492]:
d

'this is a string'

In [493]:
d[0]

't'

In [494]:
d[:5]

'this '

In [495]:
x=[0,1,2,3,4,5,6,5,65,6,56]
x[:5]

[0, 1, 2, 3, 4]

In [498]:
d[10:]

'string'

In [501]:
# use len to check the total numbers of (arguments,paramters or items) in a list

len(d)

16

In [502]:
"hello" + "howfar"

'hellohowfar'

In [503]:
"hello" + 2

TypeError: can only concatenate str (not "int") to str

In [512]:
firstname = "ayomide"
lastname =  "alex"

In [513]:
fullname= firstname + lastname
fullname

'ayomidealex'

In [514]:
fullname = firstname + " " + lastname
fullname

'ayomide alex'

In [515]:
# when printing a string together with a varriable name alwaysd sepreate the two with a comma 
print("this is my firstname", firstname)

this is my firstname ayomide


In [521]:
print("firstname:", firstname, "lastname:", lastname)

firstname: ayomide lastname: alex


In [518]:
#upper.. We use the upper method the transform a text into uppercase/capital letters
firstname

'ayomide'

In [522]:
firstname.upper()

'AYOMIDE'

In [523]:
firstname

'ayomide'

In [525]:
y= firstname.upper()
y

'AYOMIDE'

In [527]:
#we use lower to transform text into lower case/ small letters
y.lower()

'ayomide'

In [528]:
b = "Hello, World!"
print(b[2:5])

llo


In [530]:
# strip.. we use the strip method on strings to remove unncessary empty spaces from a string
f = "godf hf   akjhhd hsvd sgsb xb    "
f

'godf hf   akjhhd hsvd sgsb xb    '

In [531]:
f.strip()

'godf hf   akjhhd hsvd sgsb xb'

In [533]:
g= "      Ai is the Future        "
g

'      Ai is the Future        '

In [534]:
g.strip()

'Ai is the Future'

In [535]:
## Repalce method is your to replacing strings/letter with another string

myString= "Seyi Tinubu"

In [536]:
myString.replace("S", "F")

'Feyi Tinubu'

In [537]:
## Remove method.. this is to remove string from another string.

In [544]:
## Split() method seperates a string into sub strings using a seperator

genre = "action|drama|sci-fi|romance"

In [545]:
genre.split("|")

['action', 'drama', 'sci-fi', 'romance']

In [546]:
df= "name, title, genre, producer, budget"

In [547]:
df.split(",")

['name', ' title', ' genre', ' producer', ' budget']

In [551]:
# !pip install numpy

NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

In [552]:
import numpy as np

In [553]:
# WORKING WITH ARRAYS
a= np.array([1,2,4,6,4])
a

array([1, 2, 4, 6, 4])

In [554]:
type(a)

numpy.ndarray

In [555]:
myTuple = (1,4,3,6,6,4,7)
myTuple

(1, 4, 3, 6, 6, 4, 7)

In [557]:
arr = np.array(myTuple)
arr

array([1, 4, 3, 6, 6, 4, 7])

In [559]:
# Array indexing
arr[1]

np.int64(4)

In [561]:
arr[:5]

array([1, 4, 3, 6, 6])

In [562]:
arr[2:4]

array([3, 6])

In [563]:
arr

array([1, 4, 3, 6, 6, 4, 7])

In [564]:
# when you are indexing always make sure that the beginging value is less than the end value
arr[4:]

array([6, 4, 7])

In [565]:
arr[1:5]

array([4, 3, 6, 6])

In [566]:
arr[-2]

np.int64(4)

In [567]:
arr2 = [1,5,8,12,4,5,6,6,8,89,8,9,10]

In [569]:
arr2[7:10]

[6, 8, 89]

In [570]:
arr2[-6: -3]

[6, 8, 89]

In [575]:
# 2D
x= [2,3,5,6,7]
y= [1,6,4,9,10]
arr2D = np.array([x,y])

In [576]:
arr2D

array([[ 2,  3,  5,  6,  7],
       [ 1,  6,  4,  9, 10]])

In [578]:
my2darr = np.array([[2,5],[3,6],[1,7]])
my2darr

array([[2, 5],
       [3, 6],
       [1, 7]])

In [580]:
My3darr= np.array([[[1,2,3],[6,7,8],[9,10,11],[12,13,14]]])
My3darr

array([[[ 1,  2,  3],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]])

In [589]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [586]:
# convert 3d to 2d
arr [0,1,2]

np.int64(6)

In [588]:
arr[1,1,2]

np.int64(12)

# Shape
The shape of an array is the number of elements in each dimension.

Get the Shape of an Array
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [590]:
my2darr.shape

(3, 2)

In [591]:
arr.shape

(2, 2, 3)

In [592]:
my2d = np.array([[1,2,3,4,5],[6,7,8,9,2],[1,1,5,6,7]])
my2d

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 2],
       [1, 1, 5, 6, 7]])

In [593]:
my2d.shape

(3, 5)

In [595]:
# reshape 
print (my2d.reshape(5,3))
print ("........")
print (my2d.reshape(15,1))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [2 1 1]
 [5 6 7]]
........
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]
 [2]
 [1]
 [1]
 [5]
 [6]
 [7]]


In [596]:
myarr= np.array([[1,2,3],[5,3,7]])
myarr

array([[1, 2, 3],
       [5, 3, 7]])

In [598]:
print(myarr.reshape(3,2))
print ("......")
print(myarr.reshape(1,6))

[[1 2]
 [3 5]
 [3 7]]
......
[[1 2 3 5 3 7]]


In [599]:
# perform aritemitic operations on array

In [600]:
arrone = np.array ([1,2,4])
arrtwo = np.array ([3,1,5])

In [601]:
np.add(arrone, arrtwo)

array([4, 3, 9])

In [602]:
arrtwo + arrone

array([4, 3, 9])

In [603]:
np.multiply(arrone, arrtwo)

array([ 3,  2, 20])

In [604]:
np.divide(arrtwo, arrone)

array([3.  , 0.5 , 1.25])

In [605]:
#max method

In [606]:
np.max (arrtwo)

np.int64(5)

In [607]:
np.min(arrtwo)

np.int64(1)

In [608]:
np.mean(arrone)

np.float64(2.3333333333333335)

In [609]:
np.mean (arrone + arrtwo)

np.float64(5.333333333333333)

In [610]:
np.prod(arrone)

np.int64(8)

In [611]:
arrone

array([1, 2, 4])

In [624]:
cee= 1
for i in arrone:
    print (i)
    cee = cee* i
print (cee)

1
2
4
8


### PANDAS Series

Pandas is a Python library.

Pandas is used to analyze data.

In [626]:
!pip install pandas

   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
    --------------------------------------- 0.3/11.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.5 MB 1.5 MB/s eta 0:00:08
   --- ------------------------------------ 1.0/11.5 MB 2.1 MB/s eta 0:00:05
   ----- ---------------------------------- 1.6/11.5 MB 2.3 MB/s eta 0:00:05
   ------ --------------------------------- 1.8/11.5 MB 2.2 MB/s eta 0:00:05
   -------- ------------------------------- 2.4/11.5 MB 2.2 MB/s eta 0:00:05
   ---------- ----------------------------- 2.9/11.5 MB 2.2 MB/s eta 0:00:04
   ------------ --------------------------- 3.7/11.5 MB 2.3 MB/s eta 0:00:04
   -------------- ------------------------- 4.2/11.5 MB 2.5 MB/s eta 0:00:03
   ----------------- ---------------------- 5.0/11.5 MB 2.5 MB/s eta 0:00:03
   ------------------- -------------------- 5.5/11.5 MB 2.6 MB/s eta 0:00:03
   -----------------

In [627]:
import pandas as pd

In [116]:
# pandas series is like a column in a table
to creat a series you use pd.Series

In [628]:
mylist = [1,2,3,7]

In [630]:
df = pd.Series(mylist)
df

0    1
1    2
2    3
3    7
dtype: int64

In [631]:
df[3]

np.int64(7)

In [632]:
df= pd.Series(mylist, index=["a","b","c","d"])
df

a    1
b    2
c    3
d    7
dtype: int64

In [633]:
df["c"]

np.int64(3)

In [636]:
# Creating and series from a dictionary

calories = {"day1": 420, "day2": 340, "day3": 450}

In [637]:
df = pd.Series(calories)
df

day1    420
day2    340
day3    450
dtype: int64

In [6]:
import pandas as pd

In [7]:
x = [1,2,3,4,5,6]
x

[1, 2, 3, 4, 5, 6]

In [8]:
s = pd.Series(x)
s

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [10]:
x = [37,99,18,4]
x

[37, 99, 18, 4]

In [11]:
choice = pd.Series(x)
choice

0    37
1    99
2    18
3     4
dtype: int64

In [12]:
define = pd.Series(x, index =["Godfrey", "Moore", "AY", "Alex"])

In [13]:
define

Godfrey    37
Moore      99
AY         18
Alex        4
dtype: int64

In [15]:
define["Godfrey"]

np.int64(37)

In [16]:
l = [78, 90, 55, 30, 98]
l

[78, 90, 55, 30, 98]

In [17]:
Classwork = pd.Series(l)

In [18]:
Classwork

0    78
1    90
2    55
3    30
4    98
dtype: int64

In [19]:
define = pd.Series(l, index = ["Pablo", "micheal", "Festus", "Donald", "Ahmed"])

In [20]:
define

Pablo      78
micheal    90
Festus     55
Donald     30
Ahmed      98
dtype: int64

In [21]:
l = [78, 90, 55, 30, 98]
l

[78, 90, 55, 30, 98]

In [29]:
define = pd.Series(l)

In [30]:
l = pd.Series([78,90,55,30,98])

In [31]:
l.index = ["AYO", "BALE", "BACO", "ABLE", "DAVE"]

In [32]:
l

AYO     78
BALE    90
BACO    55
ABLE    30
DAVE    98
dtype: int64

In [36]:
l["DAVE"]

np.int64(98)

In [43]:
C = pd.Series([45, 17, 32, 49], index = ["pablo", "mike", "brave", "cole"])

Creating a Series Directly.

In [44]:
C

pablo    45
mike     17
brave    32
cole     49
dtype: int64

In [46]:
dict 

F = {"name": "Godfrey", "Age": 25, "Food": "Rice", "State": "Bayelsa"}

In [47]:
F = pd.Series(F)

In [49]:
F


name     Godfrey
Age           25
Food        Rice
State    Bayelsa
dtype: object

In [58]:
F["name"]

'Godfrey'

### Data Frames..
Data frames are both coloums and rows

In [75]:
# Creating a data Frame for dictionary

In [60]:
exercise ={
    "calories": [100,200,300,400,500],
    "minutes": [30,40,50,60,70]
}

In [61]:
exercise

{'calories': [100, 200, 300, 400, 500], 'minutes': [30, 40, 50, 60, 70]}

In [63]:
df= pd.DataFrame(exercise)

In [64]:
df

calories  minutes
0       100       30
1       200       40
2       300       50
3       400       60
4       500       70

In [65]:
data = [
    ["james", 10, "black"],
    ["tayo", 20, "white"],
    ["emma", 50, "red"]
]

In [66]:
data

[['james', 10, 'black'], ['tayo', 20, 'white'], ['emma', 50, 'red']]

In [71]:
df = pd.DataFrame(data, columns = ["names","score","color"])

In [72]:
df

names  score  color
0  james     10  black
1   tayo     20  white
2   emma     50    red

In [73]:
df.index = ["a","b","c"]

In [74]:
df

names  score  color
a  james     10  black
b   tayo     20  white
c   emma     50    red

In [76]:
df["names"]

a    james
b     tayo
c     emma
Name: names, dtype: object

In [77]:
df["color"]

a    black
b    white
c      red
Name: color, dtype: object

In [90]:
df.loc["a","names"]

'james'

In [80]:
df.loc["c","s"]

np.int64(50)

In [84]:
df.iloc[1,0]

'tayo'

In [88]:
df[["names","score"]]

names  score
a  james     10
b   tayo     20
c   emma     50

In [92]:
dett = pd.DataFrame (
    {
        "firstName": ["john", "Dayo", "Chika","daniel","james","tobi","sam","moore","jeff","alex"],
        "lastName" : ["Johnson", "Seyi", "Kingsley","sam","jamea", "ay","joo","Kingsley","victor","elijah"],
        "Age": [25,32,19,33,44,55,6,36,68,69,],
        "department": ["Sales", "IT", "Editorial", "Sales", "IT", "Editorial", "Sales", "IT", "Editorial", "IT"]
    }

    
)
dett

firstName  lastName  Age department
0      john   Johnson   25      Sales
1      Dayo      Seyi   32         IT
2     Chika  Kingsley   19  Editorial
3    daniel       sam   33      Sales
4     james     jamea   44         IT
5      tobi        ay   55  Editorial
6       sam       joo    6      Sales
7     moore  Kingsley   36         IT
8      jeff    victor   68  Editorial
9      alex    elijah   69         IT

In [93]:
dett.loc[1]

firstName     Dayo
lastName      Seyi
Age             32
department      IT
Name: 1, dtype: object

In [94]:
dett.loc[7]

firstName        moore
lastName      Kingsley
Age                 36
department          IT
Name: 7, dtype: object

In [98]:
dett[dett["Age"] > 30]

firstName  lastName  Age department
1      Dayo      Seyi   32         IT
3    daniel       sam   33      Sales
4     james     jamea   44         IT
5      tobi        ay   55  Editorial
7     moore  Kingsley   36         IT
8      jeff    victor   68  Editorial
9      alex    elijah   69         IT

In [101]:
dett ["Age"] > 30

0    False
1     True
2    False
3     True
4     True
5     True
6    False
7     True
8     True
9     True
Name: Age, dtype: bool

In [107]:
dett ["department"] == "IT"

0    False
1     True
2    False
3    False
4     True
5    False
6    False
7     True
8    False
9     True
Name: department, dtype: bool

In [115]:
dett[(dett["Age"] > 20) & (dett["department"] == "IT")]

firstName  lastName  Age department
1      Dayo      Seyi   32         IT
4     james     jamea   44         IT
7     moore  Kingsley   36         IT
9      alex    elijah   69         IT

In [1]:
import pandas as dp

In [2]:
df = pd.read_csv("2016-Movies.csv")

NameError: name 'pd' is not defined